#ifndef _MOVELIB_H
#define _MOVELIB_H

#define SERVO_DRIVE_CTL_PIN -1 //TODO
#define SERVO_DRIVE_LEFT_PWM_PIN -1 //TODO
#define SERVO_DRIVE_LEFT_PWM_NEUTRAL 0 //TODO
#define SERVO_DRIVE_RIGHT_PWM_PIN -1 //TODO
#define SERVO_DRIVE_RIGHT_PWM_NEUTRAL 0 //TODO

#endif